version: '3.1'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=file_service_db
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - 5432:5432
